//! GET GEO LOCATION TYPES
export const FETCH_LOCATION_PENDING = 'FETCH_LOCATION_PENDING';
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';